<?php
			$end = addslashes(strip_tags($_REQUEST['time_end']));
			$tach_end = explode('/', $end);
			$date_end = $tach_end[0];
			$month_end = $tach_end[1];
			$year_end = $tach_end[2];
			$end_time = mktime(23, 59, 59, $month_end, $date_end, $year_end);
			$begin = addslashes(strip_tags($_REQUEST['time_begin']));
			$tach_begin = explode('/', $begin);
			$date_begin = $tach_begin[0];
			$month_begin = $tach_begin[1];
			$year_begin = $tach_begin[2];
			$begin_time = mktime(0, 0, 0, $month_begin, $date_begin, $year_begin);
			$thongke = json_decode($class_index->thongke_doanhthu($conn, $user_id, $begin_time, $end_time), true);
			$thongke_socdo = json_decode($class_index->thongke_doanhthu_socdo($conn, $user_id, $begin_time, $end_time), true);
			$thongke_aff = json_decode($class_index->thongke_doanhthu_aff($conn, $user_id, $begin_time, $end_time), true);
			$ok = 1;
			$thongbao = 'Lấy dữ liệu thành công';
			$bien = array(
				'ok' => $ok,
				'thongbao' => $thongbao,
				'doanhthu_hoanthanh' => number_format($thongke['doanhthu_hoanthanh']) . ' đ',
				'doanhthu_giao' => number_format($thongke['doanhthu_vanchuyen']) . ' đ',
				'doanhthu_huy' => number_format($thongke['doanhthu_huy']) . ' đ',
				'doanhthu_hoan' => number_format($thongke['doanhthu_hoan']) . ' đ',
				'doanhthu_cho' => number_format($thongke['doanhthu_cho']) . ' đ',
				'doanhthu_tiepnhan' => number_format($thongke['doanhthu_tiepnhan']) . ' đ',
				'donhang_hoanthanh' => 'với ' . number_format($thongke['donhang_hoanthanh']) . ' đơn hàng',
				'donhang_giao' => 'với ' . number_format($thongke['donhang_vanchuyen']) . ' đơn hàng',
				'donhang_huy' => 'với ' . number_format($thongke['donhang_huy']) . ' đơn hàng',
				'donhang_hoan' => 'với ' . number_format($thongke['donhang_hoan']) . ' đơn hàng',
				'donhang_cho' => 'với ' . number_format($thongke['donhang_cho']) . ' đơn hàng',
				'donhang_tiepnhan' => 'với ' . number_format($thongke['donhang_tiepnhan']) . ' đơn hàng',
				'doanhthu_hoanthanh_socdo' => number_format($thongke_socdo['doanhthu_hoanthanh']) . ' đ',
				'doanhthu_giao_socdo' => number_format($thongke_socdo['doanhthu_vanchuyen']) . ' đ',
				'doanhthu_huy_socdo' => number_format($thongke_socdo['doanhthu_huy']) . ' đ',
				'doanhthu_hoan_socdo' => number_format($thongke_socdo['doanhthu_hoan']) . ' đ',
				'doanhthu_cho_socdo' => number_format($thongke_socdo['doanhthu_cho']) . ' đ',
				'doanhthu_tiepnhan_socdo' => number_format($thongke_socdo['doanhthu_tiepnhan']) . ' đ',
				'donhang_hoanthanh_socdo' => 'với ' . number_format($thongke_socdo['donhang_hoanthanh']) . ' đơn hàng',
				'donhang_giao_socdo' => 'với ' . number_format($thongke_socdo['donhang_vanchuyen']) . ' đơn hàng',
				'donhang_huy_socdo' => 'với ' . number_format($thongke_socdo['donhang_huy']) . ' đơn hàng',
				'donhang_hoan_socdo' => 'với ' . number_format($thongke_socdo['donhang_hoan']) . ' đơn hàng',
				'donhang_cho_socdo' => 'với ' . number_format($thongke_socdo['donhang_cho']) . ' đơn hàng',
				'donhang_tiepnhan_socdo' => 'với ' . number_format($thongke_socdo['donhang_tiepnhan']) . ' đơn hàng',
                'doanhthu_hoanthanh_aff' => number_format($thongke_aff['doanhthu_hoanthanh']) . ' đ',
                'doanhthu_giao_aff' => number_format($thongke_aff['doanhthu_vanchuyen']) . ' đ',
                'doanhthu_huy_aff' => number_format($thongke_aff['doanhthu_huy']) . ' đ',
                'doanhthu_hoan_aff' => number_format($thongke_aff['doanhthu_hoan']) . ' đ',
                'doanhthu_cho_aff' => number_format($thongke_aff['doanhthu_cho']) . ' đ',
                'doanhthu_tiepnhan_aff' => number_format($thongke_aff['doanhthu_tiepnhan']) . ' đ',
                'donhang_hoanthanh_aff' => 'với ' . number_format($thongke_aff['donhang_hoanthanh']) . ' đơn hàng',
                'donhang_giao_aff' => 'với ' . number_format($thongke_aff['donhang_vanchuyen']) . ' đơn hàng',
                'donhang_huy_aff' => 'với ' . number_format($thongke_aff['donhang_huy']) . ' đơn hàng',
                'donhang_hoan_aff' => 'với ' . number_format($thongke_aff['donhang_hoan']) . ' đơn hàng',
                'donhang_cho_aff' => 'với ' . number_format($thongke_aff['donhang_cho']) . ' đơn hàng',
                'donhang_tiepnhan_aff' => 'với ' . number_format($thongke_aff['donhang_tiepnhan']) . ' đơn hàng',
			);
			echo json_encode($bien);
?>