<?php
	$thaythe['title'] = 'Thống kê chung';
	$thaythe['title_action'] = 'Thống kê chung';
	$end = date('d/m/Y');
	$date_end = date('d');
	$month_end = date('m');
	$year_end = date('Y');
	$end_time = mktime(23, 59, 59, $month_end, $date_end, $year_end);
	$begin_time = $end_time - 31 * 24 * 3600;
	$begin = date('d/m/Y', $begin_time);
	$thongke = json_decode($class_index->thongke_doanhthu($conn,$user_id, $begin_time, $end_time), true);
	$thongke_socdo = json_decode($class_index->thongke_doanhthu_socdo($conn,$user_id, $begin_time, $end_time), true);
//	$thongke_aff = json_decode($class_index->thongke_doanhthu_aff($conn,$user_id, $begin_time, $end_time), true);
	$list_donhang=json_decode($class_index->list_donhang_moi_socdo($conn,$user_id, 1, 10),true);
	$list_donhang_cuaban=json_decode($class_index->list_donhang_moi($conn, $user_id, 1, 10),true);
	$bien = array(
		'footer' => $skin->skin_normal('skin_admin/footer'),
		'end' => $end,
		'begin' => $begin,
		'doanhthu_cho' => number_format($thongke['doanhthu_cho']),
		'doanhthu_tiepnhan' => number_format($thongke['doanhthu_tiepnhan']),
		'doanhthu_hoanthanh' => number_format($thongke['doanhthu_hoanthanh']),
		'doanhthu_giao' => number_format($thongke['doanhthu_vanchuyen']),
		'doanhthu_huy' => number_format($thongke['doanhthu_huy']),
		'doanhthu_hoan' => number_format($thongke['doanhthu_hoan']),
		'donhang_cho' => number_format($thongke['donhang_cho']),
		'donhang_tiepnhan' => number_format($thongke['donhang_tiepnhan']),
		'donhang_hoanthanh' => number_format($thongke['donhang_hoanthanh']),
		'donhang_giao' => number_format($thongke['donhang_vanchuyen']),
		'donhang_huy' => number_format($thongke['donhang_huy']),
		'donhang_hoan' => number_format($thongke['donhang_hoan']),
		'doanhthu_cho_socdo' => number_format($thongke_socdo['doanhthu_cho']),
		'doanhthu_tiepnhan_socdo' => number_format($thongke_socdo['doanhthu_tiepnhan']),
		'doanhthu_hoanthanh_socdo' => number_format($thongke_socdo['doanhthu_hoanthanh']),
		'doanhthu_giao_socdo' => number_format($thongke_socdo['doanhthu_vanchuyen']),
		'doanhthu_huy_socdo' => number_format($thongke_socdo['doanhthu_huy']),
		'doanhthu_hoan_socdo' => number_format($thongke_socdo['doanhthu_hoan']),
		'donhang_cho_socdo' => number_format($thongke_socdo['donhang_cho']),
		'donhang_tiepnhan_socdo' => number_format($thongke_socdo['donhang_tiepnhan']),
		'donhang_hoanthanh_socdo' => number_format($thongke_socdo['donhang_hoanthanh']),
		'donhang_giao_socdo' => number_format($thongke_socdo['donhang_vanchuyen']),
		'donhang_huy_socdo' => number_format($thongke_socdo['donhang_huy']),
		'donhang_hoan_socdo' => number_format($thongke_socdo['donhang_hoan']),
		//'doanhthu_cho_aff' => number_format($thongke_aff['doanhthu_cho']),
		// 'doanhthu_tiepnhan_aff' => number_format($thongke_aff['doanhthu_tiepnhan']),
		// 'doanhthu_hoanthanh_aff' => number_format($thongke_aff['doanhthu_hoanthanh']),
		// 'doanhthu_giao_aff' => number_format($thongke_aff['doanhthu_vanchuyen']),
		// 'doanhthu_huy_aff' => number_format($thongke_aff['doanhthu_huy']),
		// 'doanhthu_hoan_aff' => number_format($thongke_aff['doanhthu_hoan']),
		// 'donhang_cho_aff' => number_format($thongke_aff['donhang_cho']),
		// 'donhang_tiepnhan_aff' => number_format($thongke_aff['donhang_tiepnhan']),
		// 'donhang_hoanthanh_aff' => number_format($thongke_aff['donhang_hoanthanh']),
		// 'donhang_giao_aff' => number_format($thongke_aff['donhang_vanchuyen']),
		// 'donhang_huy_aff' => number_format($thongke_aff['donhang_huy']),
		// 'donhang_hoan_aff' => number_format($thongke_aff['donhang_hoan']),
		'list_donhang'=>$list_donhang['list'],
		'list_donhang_cuaban'=>$list_donhang_cuaban['list']
	);
	$thaythe['box_right'] = $skin->skin_replace('skin_ncc/box_action/dashboard', $bien);
?>